[IMP] point_of_sale: store pricelist item on Orderline
QuocDuong1306/odoo pull request #2
Opened 2024-08-23 08:39 UTC by QuocDuong1306

Currently, the applied pricelist item on an Orderline is not stored in the Point of Sale (POS) model. This limitation restricts potential enhancements and the ability to track pricing rules accurately within the POS module.

Proposed Change:

This PR introduces the functionality to store the applied pricelist item on the Orderline whenever a new price is determined for a product based on the selected pricelist. By capturing this information, we enable more flexible and advanced behaviors in future developments, such as detailed price analysis, customized discounts, improved reporting, and so on.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-23 10:12 UTC, nilshamerlinck requested changes
did you check v17/master for similar changes?

2024-08-23 10:12 UTC, nilshamerlinck commented on addons/point_of_sale/static/src/js/models.js
> +        this.order.assert_editable();
do you really need this assert in a getter?

2024-08-23 10:14 UTC, nilshamerlinck commented
your previous PR `https://github.com/odoo/odoo/pull/174143` has not been merged (yet), so I'm afraid you will need to add a similar CLA commit in this one

2024-08-23 10:17 UTC, nilshamerlinck commented
description is quite good, thanks for the effort :+1: 

can be improved a bit:

Currently, the applied pricelist item on an Orderline is not stored in the Point of Sale (POS) model.

Proposed Change:

This PR stores the applied pricelist item on the Orderline whenever a new price is determined for a product based on the selected pricelist. Doing so, we enable other modules to use this information, for example if we want to show it on the show a distinctive mark on the Receipt whenever a specific type of pricelist item has been applied.

2024-08-23 10:22 UTC, QuocDuong1306 commented
> did you check v17/master for similar changes?

Hi @nilshamerlinck , as I checked, on Odoo 17, it doesn't have any improvements for storing the pricelist item somewhere. Look like we are the first discovering people to know that :))

2024-08-26 00:55 UTC, QuocDuong1306 commented
Hi @nilshamerlinck , the PR is updated

2024-08-26 01:36 UTC, nilshamerlinck approved these changes

2024-08-26 02:27 UTC, closed without merging