fixup! [IMP] point_of_sale: Store applied pricelist item on Orderline
QuocDuong1306/odoo pull request #3
Opened 2024-09-11 09:43 UTC by QuocDuong1306

2024-09-11 10:06 UTC, nilshamerlinck requested changes
nitpicks

2024-09-11 10:06 UTC, nilshamerlinck commented on addons/point_of_sale/static/src/js/models.js
> +    get_price(pricelist, quantity, price_extra, get_pricelist_rule=false){
```suggestion
    get_price(pricelist, quantity, price_extra, get_pricelist_item=false){
```

2024-09-11 10:06 UTC, nilshamerlinck commented on addons/point_of_sale/static/src/js/models.js
> +        return get_pricelist_rule ? {price: price, pricelist_item: applied_item}: price;
```suggestion
        return get_pricelist_item ? {price: price, pricelist_item: applied_item}: price;
```

2024-09-11 10:06 UTC, nilshamerlinck commented on addons/point_of_sale/static/src/js/models.js
> +    set_pricelist_item(rule){
```suggestion
    set_pricelist_item(item){
```

2024-09-11 10:06 UTC, nilshamerlinck commented on addons/point_of_sale/static/src/js/models.js
> +        this.pricelist_item = rule;
```suggestion
        this.pricelist_item = item;
```

2024-09-11 10:06 UTC, nilshamerlinck commented on addons/point_of_sale/static/src/js/models.js
> +            pricelist_item_id: this.get_pricelist_item() ? this.get_pricelist_item().id : false,
```suggestion
            pricelist_item_id: this.pricelist_item?.id ?? false,
```

2024-09-12 01:03 UTC, QuocDuong1306 commented
Thank Nils, The PR is updated

2024-09-12 01:07 UTC, nilshamerlinck requested changes
I was thinking in the shower, maybe worth showing the new line field in a backend view somewhere?

2024-09-12 01:28 UTC, QuocDuong1306 commented
Hi nils, as I saw in sale.order: https://github.com/odoo/odoo/blob/4c91a4ba280e4709d391419cc9f6b39432bdbe5f/addons/sale/models/sale_order_line.py#L135

`pricelist_item_id` was just used to cache for calculating, and was not shown in the view: https://github.com/odoo/odoo/blob/16.0/addons/sale/views/sale_order_views.xml

2024-09-12 01:31 UTC, QuocDuong1306 commented
Do you want me to do it differently from sale.order on pos?

2024-09-12 01:35 UTC, nilshamerlinck approved these changes
thanks for the research, good as is then

2024-09-12 01:36 UTC, nilshamerlinck commented
ah but just to be sure: these new changes will be for master branch only, not for alloboissons

2024-09-13 03:10 UTC, closed without merging